// scripts/mock-papers.mjs
// 演示用 mock 论文数据，覆盖 Mamba/SOC/PINN/高光谱等核心方向

export const MOCK_PAPERS = [
  {
    title: "MambaSOC: Selective State Space Models for Soil Organic Carbon Prediction from Hyperspectral Data",
    authors: ["Wei Zhang", "Li Chen", "Xiao Wang"],
    year: 2026,
    published_date: "2026-06-15",
    source: "arxiv",
    venue: "arXiv",
    url: "https://arxiv.org/abs/2506.12345",
    doi: "",
    arxiv_id: "2506.12345",
    abstract: "We propose MambaSOC, a novel selective state space model for predicting soil organic carbon (SOC) from vis-NIR hyperspectral data. Our approach employs bidirectional spectral scanning via Mamba blocks to capture long-range spectral dependencies across 400-2500nm wavelengths. We incorporate SCORPAN-based knowledge constraints as physics-informed auxiliary losses, guiding the model with domain knowledge about soil formation factors. Experiments on the LUCAS and ICRAF-ISRIC datasets demonstrate that MambaSOC achieves RMSE of 4.2 g/kg and R² of 0.89, outperforming Transformer-based baselines while using 40% fewer parameters. Ablation studies confirm the effectiveness of both the selective scan mechanism and the soil-knowledge loss term.",
    pdf_status: "open_pdf",
    pdf_url: "https://arxiv.org/pdf/2506.12345",
    code_url: "https://github.com/example/mambasoc",
    citations: 3,
    query_pack: "mamba-ssm",
    matched_keywords: [],
    primary_tags: [],
    formula_tags: [],
    hook_types: [],
    hook_summary: "",
    possible_idea: "",
    possible_experiment: "",
    writing_position: [],
    risk_note: "",
    priority: "",
    reason: ""
  },
  {
    title: "SpectralMamba: Efficient Spatial-Spectral State Space Modeling for Hyperspectral Image Classification",
    authors: ["Yun Liu", "Hua Zhou", "Ming Li", "Jing Sun"],
    year: 2026,
    published_date: "2026-06-10",
    source: "arxiv",
    venue: "IGARSS 2026",
    url: "https://arxiv.org/abs/2506.09876",
    doi: "",
    arxiv_id: "2506.09876",
    abstract: "Hyperspectral image classification requires modeling complex spatial-spectral correlations across hundreds of bands. Existing Transformer-based methods suffer from quadratic attention complexity. We propose SpectralMamba, which employs dual-stream spatial and spectral Mamba blocks with gated fusion to efficiently capture long-range dependencies. A novel spectral scanning strategy processes bands in groups defined by spectral correlation clusters. On Indian Pines, Pavia University and Houston 2013 benchmarks, SpectralMamba achieves state-of-the-art OA of 98.7%, 99.5% and 97.8% respectively, with 3.2x faster inference than comparable Transformer models.",
    pdf_status: "open_pdf",
    pdf_url: "https://arxiv.org/pdf/2506.09876",
    code_url: "",
    citations: 1,
    query_pack: "hyperspectral",
    matched_keywords: [],
    primary_tags: [],
    formula_tags: [],
    hook_types: [],
    hook_summary: "",
    possible_idea: "",
    possible_experiment: "",
    writing_position: [],
    risk_note: "",
    priority: "",
    reason: ""
  },
  {
    title: "PINN-Soil: Physics-Informed Neural Networks with Soil Science Knowledge for Digital Soil Mapping",
    authors: ["Anna Mueller", "Pedro Santos", "Yuki Tanaka"],
    year: 2026,
    published_date: "2026-06-08",
    source: "semantic_scholar",
    venue: "Geoderma",
    url: "https://doi.org/10.1016/j.geoderma.2026.116123",
    doi: "10.1016/j.geoderma.2026.116123",
    arxiv_id: "",
    abstract: "We present PINN-Soil, a physics-informed neural network framework for digital soil mapping that integrates pedological process knowledge through PDE-based loss terms. The model incorporates soil carbon decomposition dynamics (first-order kinetics) and Jenny's SCORPAN factors as structural inductive biases. Our combined loss function includes data fidelity, PDE residual, and boundary condition terms weighted by an adaptive scheme. On 12 study sites across Europe and North America, PINN-Soil achieves significantly better generalization in data-sparse regions, reducing RMSE by 18% compared to pure data-driven approaches. The physics constraints enforce geophysically plausible predictions.",
    pdf_status: "needs_institution",
    pdf_url: "",
    code_url: "https://github.com/example/pinn-soil",
    citations: 8,
    query_pack: "pinn-soilml",
    matched_keywords: [],
    primary_tags: [],
    formula_tags: [],
    hook_types: [],
    hook_summary: "",
    possible_idea: "",
    possible_experiment: "",
    writing_position: [],
    risk_note: "",
    priority: "",
    reason: ""
  },
  {
    title: "Mamba-2: State Space Duality and Its Applications in Vision",
    authors: ["Tri Dao", "Albert Gu"],
    year: 2026,
    published_date: "2026-05-28",
    source: "arxiv",
    venue: "ICML 2026",
    url: "https://arxiv.org/abs/2405.21060",
    doi: "",
    arxiv_id: "2405.21060",
    abstract: "We revisit the connection between structured state space models (SSMs) and attention mechanisms, establishing a formal duality. Mamba-2 exploits this duality to derive semiseparable matrix representations that admit both efficient linear recurrence and parallel computation via structured matrix multiplication. The resulting architecture achieves 2-8x faster training than Mamba-1 while maintaining competitive performance on language modeling and vision tasks. We demonstrate that the Mamba-2 block can serve as a drop-in replacement for attention in vision transformers, achieving comparable accuracy on ImageNet with significantly lower memory consumption.",
    pdf_status: "open_pdf",
    pdf_url: "https://arxiv.org/pdf/2405.21060",
    code_url: "https://github.com/state-spaces/mamba",
    citations: 124,
    query_pack: "mamba-ssm",
    matched_keywords: [],
    primary_tags: [],
    formula_tags: [],
    hook_types: [],
    hook_summary: "",
    possible_idea: "",
    possible_experiment: "",
    writing_position: [],
    risk_note: "",
    priority: "",
    reason: ""
  },
  {
    title: "DeltaNet: Parallelizing Linear Recurrences with Delta Rule for Efficient Sequence Modeling",
    authors: ["Songlin Yang", "Jan Kautz", "Ali Hatamizadeh"],
    year: 2026,
    published_date: "2026-06-01",
    source: "arxiv",
    venue: "arXiv",
    url: "https://arxiv.org/abs/2406.06484",
    doi: "",
    arxiv_id: "2406.06484",
    abstract: "We propose DeltaNet, a novel linear recurrent sequence model based on the delta rule for weight updates. Unlike previous linear attention models, DeltaNet uses a delta update rule that selectively modifies the recurrent state, enabling in-context learning capabilities comparable to softmax attention while maintaining linear complexity. We derive a hardware-efficient parallel form using WY representation, enabling chunk-wise computation. DeltaNet achieves near-GPT-2 quality on language modeling while being 3x faster at inference and 2x more memory efficient. We further show strong performance on associative recall tasks that challenge previous linear models.",
    pdf_status: "open_pdf",
    pdf_url: "https://arxiv.org/pdf/2406.06484",
    code_url: "https://github.com/NVlabs/DeltaNet",
    citations: 47,
    query_pack: "mamba-ssm",
    matched_keywords: [],
    primary_tags: [],
    formula_tags: [],
    hook_types: [],
    hook_summary: "",
    possible_idea: "",
    possible_experiment: "",
    writing_position: [],
    risk_note: "",
    priority: "",
    reason: ""
  },
  {
    title: "RemoteMamba: Vision State Space Models for Remote Sensing Image Segmentation",
    authors: ["Fei Wang", "Jun Zhao", "Tao Liu", "Xian Li"],
    year: 2026,
    published_date: "2026-06-12",
    source: "arxiv",
    venue: "CVPR 2026",
    url: "https://arxiv.org/abs/2506.14567",
    doi: "",
    arxiv_id: "2506.14567",
    abstract: "We present RemoteMamba, a visual state space model tailored for high-resolution remote sensing image segmentation. Remote sensing images pose unique challenges: very large spatial extent, complex multi-scale objects, and strong anisotropy. RemoteMamba employs omnidirectional scanning paths and multi-scale state space blocks to capture both fine-grained details and global context. A lightweight decoder fuses multi-level features with gated fusion modules. On ISPRS Vaihingen, Potsdam and LoveDA benchmarks, RemoteMamba achieves mIoU of 84.3%, 86.7% and 53.2%, outperforming all previous CNN and Transformer baselines while being 40% faster on inference with RTX GPU.",
    pdf_status: "open_pdf",
    pdf_url: "https://arxiv.org/pdf/2506.14567",
    code_url: "https://github.com/example/remotemamba",
    citations: 5,
    query_pack: "vision-remote-mamba",
    matched_keywords: [],
    primary_tags: [],
    formula_tags: [],
    hook_types: [],
    hook_summary: "",
    possible_idea: "",
    possible_experiment: "",
    writing_position: [],
    risk_note: "",
    priority: "",
    reason: ""
  },
  {
    title: "A Survey of State Space Models for Vision: From S4 to Mamba-2",
    authors: ["Mingyu Liu", "Hao Chen", "Wei Sun"],
    year: 2026,
    published_date: "2026-05-20",
    source: "arxiv",
    venue: "arXiv",
    url: "https://arxiv.org/abs/2506.00123",
    doi: "",
    arxiv_id: "2506.00123",
    abstract: "This survey provides a comprehensive review of state space models (SSMs) for visual understanding, covering the evolution from S4 to Mamba and Mamba-2. We establish a unified taxonomy of SSM variants, categorizing them by state update rule, scan strategy, and computational efficiency. We survey applications across image classification, segmentation, object detection, video understanding, and multi-modal tasks. We identify key open challenges including the handling of 2D spatial relationships, efficient multi-scale modeling, and integration with diffusion models. This taxonomy serves as a roadmap for future SSM-based vision research.",
    pdf_status: "open_pdf",
    pdf_url: "https://arxiv.org/pdf/2506.00123",
    code_url: "",
    citations: 32,
    query_pack: "mamba-ssm",
    matched_keywords: [],
    primary_tags: [],
    formula_tags: [],
    hook_types: [],
    hook_summary: "",
    possible_idea: "",
    possible_experiment: "",
    writing_position: [],
    risk_note: "",
    priority: "",
    reason: ""
  },
  {
    title: "SpectralGate: Learnable Spectral Attention with Gated Linear Units for Hyperspectral Band Selection",
    authors: ["Qian Zhang", "Rui Chen", "Bing Liu"],
    year: 2026,
    published_date: "2026-06-05",
    source: "semantic_scholar",
    venue: "IEEE TGRS",
    url: "https://arxiv.org/abs/2506.07890",
    doi: "10.1109/TGRS.2026.1234567",
    arxiv_id: "2506.07890",
    abstract: "Effective band selection is critical for hyperspectral analysis. We propose SpectralGate, a learnable band attention module using gated linear units (GLU) with spectral frequency filtering. SpectralGate learns soft band importance weights through a lightweight gate mechanism operating on band correlation matrices. Unlike hard band selection, SpectralGate is fully differentiable and can be integrated into any backbone. Applied to SOC prediction from soil hyperspectral data, SpectralGate improves R² by 0.04 while reducing computation by 30% by effectively down-weighting noisy water vapor absorption bands.",
    pdf_status: "open_pdf",
    pdf_url: "https://arxiv.org/pdf/2506.07890",
    code_url: "https://github.com/example/spectralgate",
    citations: 2,
    query_pack: "hyperspectral",
    matched_keywords: [],
    primary_tags: [],
    formula_tags: [],
    hook_types: [],
    hook_summary: "",
    possible_idea: "",
    possible_experiment: "",
    writing_position: [],
    risk_note: "",
    priority: "",
    reason: ""
  },
  {
    title: "Foundation Model for Earth Observation: Scaling Vision Transformers to Remote Sensing",
    authors: ["Google Research Team"],
    year: 2026,
    published_date: "2026-04-15",
    source: "arxiv",
    venue: "arXiv",
    url: "https://arxiv.org/abs/2506.19999",
    doi: "",
    arxiv_id: "2506.19999",
    abstract: "We present EarthFoundation, a billion-parameter vision transformer pretrained on 100M remote sensing images from Sentinel-2, Landsat, and commercial satellites. Using masked autoencoder pretraining with geospatial position encoding, EarthFoundation achieves zero-shot and few-shot performance competitive with supervised methods on downstream tasks including land cover classification, change detection, and biomass estimation. Fine-tuning on 1% of labeled data matches previous state-of-the-art on all benchmarks. This demonstrates the potential of large-scale foundation models to reduce annotation burden in earth observation.",
    pdf_status: "open_pdf",
    pdf_url: "https://arxiv.org/pdf/2506.19999",
    code_url: "https://github.com/google-research/earth-foundation",
    citations: 89,
    query_pack: "vision-remote-mamba",
    matched_keywords: [],
    primary_tags: [],
    formula_tags: [],
    hook_types: [],
    hook_summary: "",
    possible_idea: "",
    possible_experiment: "",
    writing_position: [],
    risk_note: "",
    priority: "",
    reason: ""
  },
  {
    title: "Efficient Multi-Scale Feature Fusion with Large Kernel Convolutions for Dense Prediction",
    authors: ["Hao Wang", "Fang Liu"],
    year: 2026,
    published_date: "2026-06-18",
    source: "arxiv",
    venue: "arXiv",
    url: "https://arxiv.org/abs/2506.20001",
    doi: "",
    arxiv_id: "2506.20001",
    abstract: "We propose LKFusion, a multi-scale feature fusion module using large kernel convolutions (31x31) with depthwise separable decomposition. Large kernels enable global receptive field without attention's quadratic cost. Our gated multi-scale fusion aggregates features at 4 scales using a lightweight channel attention gate. On semantic segmentation benchmarks (ADE20K, COCO-Stuff), LKFusion achieves competitive mIoU with 2x fewer FLOPs than transformer-based decoders. Ablation studies show that kernel sizes above 21x21 provide diminishing returns on most tasks.",
    pdf_status: "open_pdf",
    pdf_url: "https://arxiv.org/pdf/2506.20001",
    code_url: "",
    citations: 0,
    query_pack: "efficient-components",
    matched_keywords: [],
    primary_tags: [],
    formula_tags: [],
    hook_types: [],
    hook_summary: "",
    possible_idea: "",
    possible_experiment: "",
    writing_position: [],
    risk_note: "",
    priority: "",
    reason: ""
  }
];
